### ISSUE TITLE
whats this?

### ISSUE THREAD

**Issue by daUnknownCoder** [FlafyDev/nixos-config#2]
![image](https://github.com/FlafyDev/nixos-config/assets/84800625/8a9d0dfd-a35d-4b70-ab6c-60a7421a2ea4)
and
![image](https://github.com/FlafyDev/nixos-config/assets/84800625/281e0507-9b61-42bc-aada-9cefd214f0af)

**Comment by FlafyDev** [comment]
The volume and some other things is a Flutter app running as a Wayland Layer Shell. You can find the source for the Flutter app here: https://github.com/FlafyDev/hyprland-space-rice-etc/tree/main/flutter_top
Compiling it should be relatively similar to compiling other Flutter apps. Just make sure you have pkg-config and gtk-layer-shell.

The torrent client is a frontend for Transmission I made in Flutter. It's named "Flarrent" and can be found here: https://github.com/flafydev/flarrent.

**Comment by daUnknownCoder** [comment]
> The volume and some other things is a Flutter app running as a Wayland Layer Shell. You can find the source for the Flutter app here: https://github.com/FlafyDev/hyprland-space-rice-etc/tree/main/flutter_top Compiling it should be relatively similar to compiling other Flutter apps. Just make sure you have pkg-config and gtk-layer-shell.
> 
> The torrent client is a frontend for Transmission I made in Flutter. It's named "Flarrent" and can be found here: https://github.com/flafydev/flarrent.

Woah flutter really is an eye-candy
Only good flutter thing Ik abt yet is 
![Code-2022-11-21-34](https://github.com/FlafyDev/nixos-config/assets/84800625/81b5e3de-908e-4191-96b8-2051307b0c3a)
But now there's this volume thing

**Comment by FlafyDev** [comment]
Yeah Flutter is great 💪
